name: Single-node Cluster Kubernetes Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: nginx-app:v1
      KIND_CLUSTER_NAME: single-node-cluster

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t $DOCKER_IMAGE .
          docker tag $DOCKER_IMAGE ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE
          docker push ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE

      - name: Set Up Kind
        uses: kubernetes-sigs/kind@v3
        with:
          version: v0.17.0

      - name: Create Kind Cluster
        run: |
          kind delete cluster --name $KIND_CLUSTER_NAME || true
          kind create cluster --name $KIND_CLUSTER_NAME

      - name: Load Docker Image into Kind
        run: kind load docker-image ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE --name $KIND_CLUSTER_NAME

      - name: Install NGINX Ingress Controller
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
          kubectl wait --namespace ingress-nginx \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/component=controller \
            --timeout=90s

      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f nginx-deployment.yml
          kubectl apply -f singlenode-ingress.yml
          
      - name: Verify Deployments
        run: |
          kubectl get pods
          kubectl get services
          kubectl get ingress
